site_name: Documentation de Bibliotheque

nav : 
  - Inicio : 'index.md'
  - 'Guía de Usuario': 
    - 'Sistema de Autenticación' : 'autenticated.md'
  - Acerca de : 'about.md'

theme : readthedocs


